# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    # use the empty dummy box
    config.vm.box = "ubuntu/trusty64"

    # default provisioning script
    # https://www.vagrantup.com/docs/provisioning/shell.html
    config.vm.provision :shell, path: "./bootstrap.sh"
	
	# configure network
	config.vm.network "private_network", ip: "192.168.56.101"

    # VirtualBox Provider-specific configuration
    config.vm.provider "virtualbox" do |vb, override|

        # set the name
        vb.name = "jmeter-master"

        # set the CPU, memory, graphics
        # @see https://www.virtualbox.org/manual/ch08.html
        vb.cpus = 1
        vb.memory = "1024"
        vb.gui = false

        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        override.vm.synced_folder "./", "/vagrant"

        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        override.vm.network "forwarded_port", guest: 60000, host: 60000

        # setup local apt-get cache
        if Vagrant.has_plugin?("vagrant-cachier")
            # Configure cached packages to be shared between instances of the same base box.
            # More info on the "Usage" link above
            override.cache.scope = :box
        end

        # disable vbguest auto-upgrade
        if Vagrant.has_plugin?("vagrant-vbguest")
            # https://github.com/dotless-de/vagrant-vbguest
            config.vbguest.auto_update = false
        end
    end
end
